services:
  # A Docker web service
  - type: web
    name: todoapp
    runtime: docker
    repo: https://github.com/lfalcaolopes/TodoApp.git # optional
    plan: free # optional (defaults to starter instance type)
    dockerfilePath: ./backend/Dockerfile # optional (defaults to Dockerfile)

databases:
  - name: TodoAppApi
    plan: free