version: '3.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: TodoAppApi
    ports:
      - "5432:5432"
  backend:
    build: ./
    environment:
      DatabaseServer: "db"
      DatabasePort: "5432"
      DatabaseUser: "postgres"
      DatabasePassword: "pass123"
      DatabaseName: "TodoAppApi"
    ports:
      - "5015:80"
    depends_on:
      - db